// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var drainOptions = []prompt.Suggest{
	prompt.Suggest{Text: "--delete-local-data", Description: "Continue even if there are pods using emptyDir (local data that will be deleted when the node is drained)."},
	prompt.Suggest{Text: "--dry-run", Description: "If true, only print the object that would be sent, without sending it."},
	prompt.Suggest{Text: "--force", Description: "Continue even if there are pods not managed by a ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet."},
	prompt.Suggest{Text: "--grace-period", Description: "Period of time in seconds given to each pod to terminate gracefully. If negative, the default value specified in the pod will be used."},
	prompt.Suggest{Text: "--ignore-daemonsets", Description: "Ignore DaemonSet-managed pods."},
	prompt.Suggest{Text: "--pod-selector", Description: "Label selector to filter pods on the node"},
	prompt.Suggest{Text: "-l", Description: "Selector (label query) to filter on"},
	prompt.Suggest{Text: "--selector", Description: "Selector (label query) to filter on"},
	prompt.Suggest{Text: "--timeout", Description: "The length of time to wait before giving up, zero means infinite"},
}
