// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var configSetOptions = []prompt.Suggest{
	prompt.Suggest{Text: "--set-raw-bytes", Description: "When writing a []byte PROPERTY_VALUE, write the given string directly without base64 decoding."},
}
